### ISSUE TITLE
Consolidate documentation

### ISSUE THREAD

**Issue by dnephin** [Yelp/Tron#135]
Tron has 3 sets of documentation:
- the github wiki (including the README.md)
- the [package documentation](http://packages.python.org/tron/) (docs/)
- the man pages (which are also included as part of the package documentation)

I would like to:
- move the github wiki documentation into the package documentation and replace with a link to the package documentation
- remove any duplication between the man pages and package documentation
- create additional developer documentation (design diagrams, etc) and include as part of the package documentation

**Comment by solarkennedy** [comment]
I've turned off the wiki entirely for now.
We'll keep a README but otherwise focus on things in the docs folder.
