### ISSUE TITLE
Comment field on jobs and actions

### ISSUE THREAD

**Issue by jfennell** [Yelp/Tron#143]
It would be nice to have a field that allows you to leave a comment (that could be showing in `tronview`) on both actions and jobs in the tronfig. It is pretty easy to get a lot of jobs and a lot of steps and having something that allows and encourages documentation would be rather helpful.

**Comment by solarkennedy** [comment]
I'm going to close this as won't fix. We had similar fields before that were like this (owner, notes, summary), but they didn't end up being used.
