### ISSUE TITLE
DST time change causes funky behavior with scheduled execution start

### ISSUE THREAD

**Issue by sudarshang** [Yelp/Tron#180]
.139                         SUCC  spambatch3          2012-11-05 00:30:00
                             Start: 2012-11-04 23:30:00  End: 2012-11-04 23:36:20  (0:06:20)
.138                         SUCC  spambatch3          2012-11-04 00:30:00
                             Start: 2012-11-04 00:30:00  End: 2012-11-04 02:39:30  (2:09:30)

From .139 this batch was supposed to run on '2012-11-05 00:30:00' however it ended up starting on 2012-11-04 23:30:00. Note the DST time change was on 2012-11-04. So the DST time change caused the batch to start 1 hour earlier than its scheduled time.

**Comment by solarkennedy** [comment]
I'm going to close this. We've done a lot of changes to the DST code, this is probably fixed by now.

**Comment by irskep** [comment]
What a relief. DST logic was a nightmare for me when I was fresh out of school working on this in 2012. 😅
