### ISSUE TITLE
Gracefully reconfigure service on node change

### ISSUE THREAD

**Issue by dnephin** [Yelp/Tron#228]
If a `Node`'s connection configuration (timeout, host key, jitter, etc) changes all services on that node will be reconfigured (causing them to be disabled).

Services should only care about a nodes hostname and username for purposes of reconfiguration. However, they will still need to receive the new `NodePool` class so that old `NodePool`s and `Node`s can be GC'ed.

Additionally changes in the number of instances should not disable the service. The old service should just receive the new config, and kill/start instances as necessary.

**Comment by solarkennedy** [comment]
We no longer have tron service support.
