### ISSUE TITLE
tronweb service view dashboard

### ISSUE THREAD

**Issue by dnephin** [Yelp/Tron#243]
The service view in tronweb is pretty minimal. It has a list of the instances and the config.  Tron shouldn't try to do the work of nagios, ganglia or firefly/statmonster, but it would be great to include some of those details on the service view page.

Maybe we could include a list of urls in the `tronfig` for a service that would be loaded into iframes on the tronweb view for services.

**Comment by solarkennedy** [comment]
I'm going to close this as wont-fix as we are going to work on deprecating the service functionality of tron.
