### ISSUE TITLE
Monitoring Framework

### ISSUE THREAD

**Issue by irskep** [Yelp/Tron#25]
Tron needs a framework for doing monitoring.

Some potential monitoring systems:
- Email notification of failures
- Nagios notifications
- IRC updates
- Logging

Most we need a flexible framework of recording tron events and deciding what to pass onto configured monitors. Some of these may be integrated with how we do the web service framework. As in a nagios monitor could fairly easily use the web service interface to find the status of jobs. However sending an email on a failure would not work well with this system.

We now have support for crash emails, which is part of solving this guy.

Copied from rhettg/tron#2

**Comment by solarkennedy** [comment]
I've started a prototype for monitoring in #335.

**Comment by solarkennedy** [comment]
@irskep I'm going to close this ticket, as we have the check_tron_jobs command now. It isn't as flexible as running arbitrary commands for hooks, but it is useful for yelp developers as it uses the same `pysensu-yelp` interface available to them in other tools (like paasta).

**Comment by irskep** [comment]
OK! I haven't worked on Tron since 2012, so you know best. :-)
