### ISSUE TITLE
Trond logfile location hardcoded?

### ISSUE THREAD

**Issue by federicosacerdoti** [Yelp/Tron#274]
From reading trond 0.6.1.1 it seems the only way to change the logfile location (/var/log/tron) is to provide a new logging.conf file. This 40-line file is not convenient to alter, especially for an init-script that may want to change the logfile quickly (move from production to development, etc).

Is there some way to provide the logfile on the commandline or in the environment? My specific use-case is to start trond as a non-root user with no write access to /var/log.

Thanks,
FDS

**Comment by solarkennedy** [comment]
I'm going to wont-fix this. We will stick with logging.conf.
