### ISSUE TITLE
Insufficient error logging

### ISSUE THREAD

**Issue by federicosacerdoti** [Yelp/Tron#275]
I am new to tron, but I set it up and ran a few jobs on a single "localhost" node recently. I like the project and the interface very much, having _tronctl enable/disable_ alone makes me want to switch from cron.

However I had trouble getting my first job to run. I eventually diagnosed this to not providing a known_hosts_file (with ssh_agent: false). While tron did issue WARNINGs about this, it wasnt clear that my jobs were not going to run until this was addressed.

Specifically all my jobs would start, but remain in the _starting_ state forever. No errors were in the logs, which was confusing. 

If such config errors could be flagged in the main log with something like:

> Job Test.1 not starting because of bad config

**Comment by solarkennedy** [comment]
I'm going to close as lost. For sure by now this has been fixed.
