### ISSUE TITLE
Job Notifications

### ISSUE THREAD

**Issue by agarbato** [Yelp/Tron#303]
Hi,

Thanks for your work. Looks very promising.
I started to play with it and I must say I really like it.

However something is not really well documented for me.. notification.
When a job fails I don't receive any email. I receveid a couple but only when tron threw some execptions.
I tried to activate debug logging but I can't even see any attempt to send mails.

Is notification meant for tron  or job failures?
I think a scheduler which won't tell you when a job fail is bad.. really.
It should also be nice to have a per job notication option settings.

Thanks
A.

**Comment by yyejun** [comment]
There is no job failure notification.

**Comment by agarbato** [comment]
Ok got it. I think this should be better explained on the docs cause for some people notification is a very important factor when choosing a schedule tool.

Any plan to implement it?  
How do you monitor your jobs? Any suggestion?

**Comment by yyejun** [comment]
We do not have any plan at the moment.

You can query tron api endpoint to get latest job exit code.

**Comment by agarbato** [comment]
I see api calls from tron log but since there's no docs  I'm not sure how I can get latest job exit code.

Can you provide a valid example or point me to some documentation about api?

Thanks & Regards.

**Comment by solarkennedy** [comment]
We are taking this in the direction of using Sensu to send notifications when jobs fail.
https://github.com/Yelp/Tron/blob/master/bin/check_tron_jobs.py
See that script for examples on how to query tron to see job statuses.
