### ISSUE TITLE
Enhancement: "tron restart", but for actions rather than jobs.

### ISSUE THREAD

**Issue by mittonk** [Yelp/Tron#309]
- https://pythonhosted.org/tron/man_tronctl.html

documents:

> tronctl restart job_run_id
> tronctl restart job0.4

I'm instead reaching for the ability to restart an action:

> tronctl restart action_run_id
> tronctl restart job0.4.action3

**Comment by solarkennedy** [comment]
@keymone did this!`tronctl retry` will retry actions.
