### ISSUE TITLE
Tron uses an ancient ssh key exchange algorithm

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/Tron#323]
Just here so I don't forget:

Trying to run some xenial batch boxes, Tron fails.

In ``/var/log/auth.log`` on the batch box, there are messages hinting at an old protocol that openssh dropped a while ago.

```
error kex protocol error type 30 seq 1
```

This'll probably just need a bump in the twisted library, but we're on a (7 year!) old version of twisted, so it won't 'just work'

**Comment by chjohnst** [comment]
I have ran into this myself!

**Comment by solarkennedy** [comment]
@keymone (?) fixed this with a twisted upgrade.
