### ISSUE TITLE
Unsafe use of `global`  in tron/serialize/runstate/yamlstore.py

### ISSUE THREAD

**Issue by asottile** [Yelp/Tron#326]
https://github.com/Yelp/Tron/blob/e1d1e626599f180ee7eb229082208050a4f0fb99/tron/serialize/runstate/yamlstore.py#L27-L29

The [python spec states](https://docs.python.org/2/reference/simple_stmts.html#the-global-statement) (emphasis mine):

> Names listed in a global statement must not be defined as formal parameters or in a for loop control target, class definition, function definition, **or import statement**.

**Comment by asottile** [comment]
How did you find this @asottile?

great question! I was looking through [my open issues](https://github.com/Yelp/Tron/issues?q=is%3Aopen+is%3Aissue+author%3Aasottile) (via https://github.com/issues) and was trying to figure out if it was still a bug and I could close it.

**Comment by Rob-Johnson** [comment]
:( thanks for bumping this @asottile 

I'm in two minds as to whether to fix it or just bin this particular bit of code entirely.
