### ISSUE TITLE
Tab complete tronview commands

### ISSUE THREAD

**Issue by irskep** [Yelp/Tron#35]
job and action names are stored, so this seems possible

Copied from [issue #55 on rhettg's repo](https://github.com/rhettg/Tron/issues/55)

**Comment by solarkennedy** [comment]
This would be cool. I've asked @jglukasik to convert tron to use argparse instead of optparse, which will allow us to use https://argcomplete.readthedocs.io/en/latest/

**Comment by solarkennedy** [comment]
@jglukasik  did this.
