### ISSUE TITLE
tron should support weights for items in pools

### ISSUE THREAD

**Issue by Roguelazer** [Yelp/Tron#56]
If, say, you were to have a set of batch machines that you wanted to run batch processes on, and some of these machines were small (8 cores, 32GB RAM) and some were large (24 cores, 96GB of RAM), it would be most excellent to be able to express this to tron. So it would perhaps run more jobs on the bigger machines. Changing pools to optionally be mappings from node name to weight (with the default weight being 1) would probably solve this problem.

**Comment by solarkennedy** [comment]
Closing as wont-fix, as we are moving this to a mesos framework instead of traditional pools.
