### ISSUE TITLE
How to specify retries_delay

### ISSUE THREAD

**Issue by jarednielsen** [Yelp/Tron#691]
It looks like the Python code specifies a `datetime.timedelta()` object, but it's unclear how to specify that in a YAML string.

**Comment by solarkennedy** [comment]
It is true that it is timedelta in the code. At config parse time we allow human readable units that eventually get turned into a time delta:
https://github.com/Yelp/Tron/blob/38d916ce39479cef9a9aadacb1f9b3683256d74f/tron/config/config_utils.py#L163

It is pretty liberal:
https://github.com/Yelp/Tron/blob/38d916ce39479cef9a9aadacb1f9b3683256d74f/tron/config/config_utils.py#L148

**Comment by jarednielsen** [comment]
Perfect, thank you!
