### ISSUE TITLE
Tron daemon to run on slaves as an alternative to persistent SSH connections

### ISSUE THREAD

**Issue by irskep** [Yelp/Tron#81]
It is currently difficult to upgrade Tron due to it holding SSH connections open for the purpose of controlling a process. It might be better to let the user optionally install a daemon on a slave to handle running the processes, and let the central (scheduling/reporting process) poll this daemon for data.

The slave daemon would have no features other than to start processes, store their output, and report it via an HTTP interface. I already implemented something with almost exactly these features in my [mrjobd branch for mrjob](https://github.com/irskep/mrjob/blob/daemonized_260/mrjob/tools/mrjobctl.py).

**Comment by solarkennedy** [comment]
I'm going to close this as won't-fix, as we have chosen to rewrite Tron to use Mesos instead of the ssh or daemon approach.
