### ISSUE TITLE
tronview/tronctl should give autocorrect hints

### ISSUE THREAD

**Issue by irskep** [Yelp/Tron#98]
The current error message ("what is a X?") is really unhelpful. It should give a list of suggestions instead.

**Comment by solarkennedy** [comment]
@chlgit would you like to work on this nice-to-have?

**Comment by chlgit** [comment]
Sure. Do we need to have a ticket for this?

**Comment by solarkennedy** [comment]
na

**Comment by chlgit** [comment]
OK, we just have one https://jira.yelpcorp.com/browse/TRON-260

**Comment by solarkennedy** [comment]
I added this.
